### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by leos**
Adding flow-ide as a known provider to hyperclick

### CODE REVIEW

**Comment by leos** [comment]
@hansonw - can you merge this? or is there something else I need to do?

**Comment by hansonw** [comment]
Sorry, this slipped through! I'm going to add a wiki in the Hyperclick repo
instead, lemme get to that today.

**Comment by leos** [comment]
Sounds good, thanks @hansonw !

**Comment by hansonw** [comment]
https://github.com/facebooknuclide/hyperclick/wiki/Known-Providers

**Pull request closed without merging**
