### PR TITLE
Keymap to create new file with tree view path

### PR DESCRIPTION
**Pull request by marduke182**
I always try not to use the mouse when i'm coding and right now if I need create a new file I must use mouse right click `new -> file` option.

The attempt of this pull request is allow file creation only with the keyboard for example `ctrl-0` and `cmd+n`

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @zertosh to be a potential reviewer.

**Comment by zertosh** [comment]
cc: @shushz

**Comment by shushz** [comment]
I don't think its a good thing to change the Cmd-n behavior. You can always do it in your keymaps file if you find it more convenient, but I think that turning it on by default with Nuclide might lead to an unnecessary confusion.

Notice that core atom also doesn't do it.

**Comment by marduke182** [comment]
They use key **a** in the original tree view to add a new file. But nuclide use this key to search pattern.

For more information original tree view https://github.com/atom/tree-view/blob/master/keymaps/tree-view.cson#L74

**Pull request closed without merging**
