### PR TITLE
Navigation Stack in the FAQ and keyboard shortcuts

### PR DESCRIPTION
**Pull request by JoelMarcey**

### CODE REVIEW

**Comment by phord** [comment]
Why are the keys "backwards"?  Ctrl-< goes forward; Ctrl-> goes backwards.  This is counterintuitive and exactly the opposite of how other browsers work.

**Comment by nmote** [comment]
Yeah if that's the case that's an error. On OS X at least, ctrl-< goes backwards. PRs are welcome.

**Comment by phord** [comment]
kthx.  The commit that closed this only documented the existing, backward, behavior, I guess.  But it documents it backwards for the Mac, too.  Does that mean the doc in this commit is wrong for the Mac?

    Forward navigation: `Ctrl-,` (`Ctrl-<` on Linux and Windows)
    Backward navigation: `Ctrl-.` (`Ctrl->` on Linux and Windows)

**Comment by nmote** [comment]
Yeah, the docs here are wrong for OS X. The docs are correct for Linux, but of course the keybindings themselves are backwards. Should be an easy fix if you'd like to contribute it.

**Comment by JoelMarcey** [comment]
I actually noticed that too when I did the pull request, but looking at the keybindings.cson...

https://github.com/facebook/nuclide/blob/122fc05acb4441d9f2a95b822c583a2804165977/pkg/nuclide-navigation-stack/keymaps/navigation-stack.json

```

{
  ".platform-darwin atom-workspace": {
    "ctrl-.": "nuclide-navigation-stack:navigate-forwards",
    "ctrl-,": "nuclide-navigation-stack:navigate-backwards"
  },
  ".platform-win32 atom-workspace, .platform-linux atom-workspace": {
    "ctrl-<": "nuclide-navigation-stack:navigate-forwards",
    "ctrl->": "nuclide-navigation-stack:navigate-backwards"
  }
}
```

**Pull request closed without merging**
