### PR TITLE
Enable Objective-C bracket completion by default

### LINKED ISSUE #960: [objc] Enable Objective-C bracket insertion by default
(Migrated from Facebook task t15118085.)

Objective-C bracket balancing was originally added in 2015, but was never enabled by default. It is currently hidden behind the config value `enableAutomaticSquareBracketInsertion` in `pkg/nuclide-objc/package.json$16`.

I suspect this is disabled for the majority of developers using Nuclide -- it was for me. Confirm that no major blockers exist, and turn it on for everyone.

### PR DESCRIPTION
**Pull request by eliperkins**
Closes #960

### CODE REVIEW

**Comment by zertosh** [comment]
hmm @hansonw is there a reason this isn't the default?

**Comment by hansonw** [comment]
No idea. Maybe the author @oclbdk knows?

**Comment by oclbdk** [comment]
It was experimental and relied on some crude heuristics, so we didn't feel confident in enabling it for everybody. However, I don't see a reason not to enable it if people have been using it without issues

I'll leave it to someone on the core Nuclide to merge this

**Comment by modocache** [comment]
Thanks, everyone! 😍

**Pull request closed without merging**
