### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by smkhalsa**

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey and @matthewjohnston4 to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by johnislarry** [comment]
Thanks, sign the CLA and we can check it in

**Comment by shushz** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
I cannot do that @shushz, because @smkhalsa does not have an active CLA on file.

**Comment by nmote** [comment]
Feel free to reopen if you sign the CLA

**Comment by JoelMarcey** [comment]
I just went ahead and made a pull request with the fix in https://github.com/facebook/nuclide/pull/760

**Pull request closed without merging**
