### PR TITLE
Update documentation for the linter update.

### PR DESCRIPTION
**Pull request by k2b6s9j**
`linter-plus` was merged into `linter` this morning.

Ref AtomLinterPlus/linter-plus#9

### CODE REVIEW

**Comment by k2b6s9j** [comment]
I just signed the CLA, what now?

**Comment by ssorallen** [comment]
Thanks for the update, @k2b6s9j. We will merge internally and push back to the GitHub repo to accept your PR.

**Comment by k2b6s9j** [comment]
Awesome!

**Comment by etcinit** [comment]
:+1: I was about to create a PR for this

**Comment by k2b6s9j** [comment]
Yeah. Once my PRs merge I'm taking `linter-plus` down.

**Comment by ssorallen** [comment]
We got `linter` merged internally. If everything looks good, I will merge/push/deploy everything tomorrow morning. Thanks for the docs update and the updates to the Linter.

**Comment by k2b6s9j** [comment]
Looks good to me.

Look good? @steelbrain

**Comment by steelbrain** [comment]
@k2b6s9j Yep, the `linter-plus` package can now be unpublished.

**Comment by k2b6s9j** [comment]
@steelbrain I'm waiting on these to be merged.

**Pull request closed without merging**
