### PR TITLE
Create blog post for v0.111.0

### PR DESCRIPTION
**Pull request by ssorallen**

### CODE REVIEW

**Comment by zertosh** [comment]
:star2: :+1: :star2:

**Comment by ssorallen** [comment]
@jamesgpearce My `push -f` nuked your comment because it was on the previous SHA. I'm too used to the workflow now. I added "The Unified Package" to the title to make it more grandiose.

**Comment by zertosh** [comment]
Because he made the comment on the commit itself and not on a line in the commit.

**Comment by JoelMarcey** [comment]
shipit!

**Comment by jamesgpearce** [comment]
:ship: when you're ready!

**Comment by zertosh** [comment]
squash :stuck_out_tongue:

**Comment by ssorallen** [comment]
It done be squashed.

**Pull request merged**
