### PR TITLE
Correct menu options path to Panes in docs

### PR DESCRIPTION
**Pull request by simon-johansson**
Minor fix... At least the Panes options are under `View | ...` on OSX

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ssorallen** [comment]
That Panes functionality has actually been removed from Nuclide because new commands were added in Atom v1.6 that enabled users to add that themselves.

Could you remove the entire `Panes` section instead?

**Comment by facebook-github-bot-9** [comment]
@simon-johansson updated the pull request.

**Comment by simon-johansson** [comment]
Ok, sure. I have updated the PR.

**Comment by nmote** [comment]
@ssorallen -- ping. Does this look good now?

**Comment by ssorallen** [comment]
@nmote It does, but for some reason the referenced file in this PR is `_docs/editor/basics.md` whereas the real file lives in `docs/_docs/editor/basics.md` (extra "docs" directory). It can't successfully patch.

**Comment by ssorallen** [comment]
@simon-johansson Can you rebase this onto master? There is now a top-level "docs" directory in which the "_docs" directory lives.

**Comment by simon-johansson** [comment]
I created a new PR. Same fix but for master branch, #549

**Pull request closed without merging**
