### PR TITLE
Photos

### PR DESCRIPTION
**Pull request by zardra**
Ran all older screenshots in static/images/docs thru photo optimizer (ImageOptim).  Relates to Issue #744.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey to be a potential reviewer.

**Comment by JoelMarcey** [comment]
cc @zertosh

**Comment by JoelMarcey** [comment]
@zertosh -- want to get your blessing on this before I land it. This affects 177 images. Updates seem reasonable?

**Comment by zertosh** [comment]
👍 I tested re-running `platform-android-simulator-output.png` through ImageOptim, and didn't compress any further. For the record, here's a summary of the size differences:

```
docs/static/images/docs/platform-android-simulator-output.png                    | Bin 211183 -> 98809 bytes
docs/static/images/docs/platform-android-toggle-simulator.png                    | Bin 36554 -> 14710 bytes
docs/static/images/docs/platform-ios-buck-build.png                              | Bin 139667 -> 59679 bytes
docs/static/images/docs/platform-ios-native-autocomplete.png                     | Bin 240963 -> 118538 bytes
docs/static/images/docs/platform-ios-simulator-output.png                        | Bin 186299 -> 85347 bytes
docs/static/images/docs/platform-ios-toggle-simulator.png                        | Bin 39771 -> 16298 bytes
docs/static/images/docs/platform-react-native-feature-autocomplete.png           | Bin 356396 -> 174512 bytes
docs/static/images/docs/platform-react-native-running-buck-toolbar.png           | Bin 20879 -> 8667 bytes
docs/static/images/docs/platform-react-native-running-server-command.png         | Bin 41578 -> 19450 bytes
docs/static/images/docs/platform-react-native-running-server.png                 | Bin 143827 -> 66898 bytes
docs/static/images/docs/promo-flow.png                                           | Bin 247365 -> 103889 bytes
docs/static/images/docs/promo-hack.png                                           | Bin 548886 -> 277499 bytes
docs/static/images/docs/promo-mercurial.png                                      | Bin 256330 -> 112882 bytes
docs/static/images/docs/promo-remote-development.png                             | Bin 245337 -> 102257 bytes
docs/static/images/docs/promo-rn-debugging.png                                   | Bin 177321 -> 96870 bytes
docs/static/images/docs/promo-working-sets.png                                   | Bin 341246 -> 155686 bytes
docs/static/images/docs/quick-start-getting-started-add-project.png              | Bin 19110 -> 7868 bytes
docs/static/images/docs/quick-start-getting-started-diff-view.png                | Bin 136491 -> 72812 bytes
docs/static/images/docs/quick-start-getting-started-file-tree-view.png           | Bin 47156 -> 19905 bytes
docs/static/images/docs/quick-start-getting-started-home-page.png                | Bin 260768 -> 106100 bytes
docs/static/images/docs/quick-start-getting-started-quick-launch.png             | Bin 84537 -> 37625 bytes
docs/static/images/docs/quick-start-getting-started-quick-open.png               | Bin 35415 -> 17640 bytes
docs/static/images/docs/quick-start-getting-started-remote-connection-dialog.png | Bin 32217 -> 16581 bytes
```

**Comment by JoelMarcey** [comment]
I will land this soon - I am going to have to land this manually, given all the binary files.

**Pull request closed without merging**
