### PR TITLE
Corrected hyperlink in other.md

### PR DESCRIPTION
**Pull request by eeree**
Hyperlink to Hack typechecker has been corrected and now links to correct page

### CODE REVIEW

**Comment by zertosh** [comment]
@facebook-github-bot import

**Comment by zertosh** [comment]
hmm... @facebook-github-bot shipit

**Comment by zertosh** [comment]
Oh, hey @eeree, can you make the PR against `docs` in master and not the gh-pages branch please? Thanks!

**Comment by eeree** [comment]
Sure. Already done!

**Comment by eeree** [comment]
https://github.com/facebook/nuclide/pull/462

**Pull request closed without merging**
