### PR TITLE
Resolves issue facebook/nuclide#673

### PR DESCRIPTION
**Pull request by danmademe**
- Updated node-debugger to version from PR https://github.com/node-inspector/node-inspector/pull/932/files

Solved immediate issue.

NOTE: I'm not sure using node-debugger is wise anymore, the project looks abandoned. My guess is because node includes this now internally.
https://nodejs.org/api/debugger.html

### CODE REVIEW

**Comment by danmademe** [comment]
Ok I filled out the CLA

**Comment by johnislarry** [comment]
Thank you @danmademe!

**Comment by Mohamed-Abo-El-Soud** [comment]
@danmademe You mean the nuclide debugger? I totally use it with react native because running the debugger from chrome makes javascript calls REALLY SLOW makes me unable to test without losing my sanity. Please don't kill this.

**Comment by danmademe** [comment]
I don't work at Facebook. But it's not me that's gonna kill it it's the node-debugger package is now no longer maintained. Plus node has its own way of doing this. 

It's slow for you because your doing it in chrome. That's not an ideal way. The most ideal way would be to use the built in debugger in node and access it in the IDE. 

From memory the new method can be connected to via some web socket of sorts. So when someone works on a way of joining the two then your good to go. 

Also. Debuggers are supposed to be slow. That's just the way things are. If you hate the speed of debugging you should try debugging large scale Java applications. That is really really slow. JavaScript debugging is really fast by comparison.

**Pull request closed without merging**
