### PR TITLE
Remote Development

### PR DESCRIPTION
**Pull request by zardra**
Edited Remote Development for grammar, and updated an image.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @JoelMarcey, @zertosh and @matthewjohnston4 to be potential reviewers.

**Comment by zertosh** [comment]
👍 nice! but can you run the pngs through https://imageoptim.com please?

**Comment by JoelMarcey** [comment]
@zertosh We wanted to eventually do that with all our images, right?

**Comment by zertosh** [comment]
@JoelMarcey yeah, but we should be doing the ones we're adding - don't want to bloat the repo

**Comment by JoelMarcey** [comment]
Oh, yeah, agree. We will do it on all new images. Just gotta get around doing it on the the old images :)

**Comment by zardra** [comment]
New image has been optimized.

**Pull request closed without merging**
