### PR TITLE
Show class fields in flow outline.

### PR DESCRIPTION
**Pull request by pvolok**
This new outline feature is awesome. But it does not show fields for classes. I think it's a common pattern to define some methods as fields like this:

```js
class Component {
  state = {};

  render() {
    return <button onClick={this.handleClick} />;
  }

  handleClick = (event) => {
  };
}
```

It would be nice if such methods would be shown as well. This PR draft makes above class to appear like this:

```
class Component
  state=
  render()
  handleClick=(event)
```

If you are cool with this change, I'll add tests.

### CODE REVIEW

**Comment by nmote** [comment]
See also #437 for a few other things I want to support, if you are feeling inspired to keep working on this.

I'm not totally sure how I feel about displaying the equals sign but I'm willing to land it and see how it works in practice.

Update the tests and I'll merge.

**Comment by pvolok** [comment]
I added tests for class fields. Unfortunately I'm short on time this week and won't yet be able to address the issue you linked. Maybe later :)

**Comment by nmote** [comment]
@facebook-github-bot import

**Comment by nmote** [comment]
I made two minor tweaks -- removed trailing whitespace to pass lint, and changed the test file to `@noflow` since it now has Flow errors. Those were both needed to pass the pre-commit tests and I didn't want to have another back-and-forth before landing.

Thanks for putting this together! Totally understand re: being busy. I just wanted to make you aware of the other plans in case you were interested.

**Pull request closed without merging**
