### PR TITLE
Point linter install to the updated linter package in documentation.

### PR DESCRIPTION
**Pull request by k2b6s9j**
Ref AtomLinterPlus/linter-plus#9.

### CODE REVIEW

**Comment by ssorallen** [comment]
Thanks for the PRs, @k2b6s9j. We will merge these.

**Comment by k2b6s9j** [comment]
Great. Once that is done I'll be removing `linter-plus` from APM.

**Comment by AsaAyers** [comment]
linter-plus is also referenced in the readme.

> ... work better when the linter-plus package is installed. Note that linter-plus is separate from Nuclide and is ultimately supposed to merge with the linter package.

**Comment by k2b6s9j** [comment]
@AsaAyers I cover that in #72

**Pull request merged**
