### PR TITLE
Update README for running docs locally to have Homebrew.

### PR DESCRIPTION
**Pull request by zardra**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JoelMarcey** [comment]
Looks great!

**Comment by JoelMarcey** [comment]
@facebook-github-bot shipit

**Comment by JoelMarcey** [comment]
@facebook-github-bot import

**Pull request closed without merging**
