### PR TITLE
Add missing describe.skip and it.skip in the outline view

### LINKED ISSUE #620: Outline view doesn't support describe.skip or it.skip
### Issue and Steps to Reproduce
I have JS mocha tests and the outline view is reporting everything correctly, except `describe.skip` and `it.skip`.

Note that `describe.only` and `it.only` are both supported.

### Expected Behavior
The outline view should display `describe.skip` and `it.skip`.

### Actual Behavior
The outline view does not display `describe.skip` and `it.skip`.

### Versions
* Atom: 1.8.0
* Nuclide: 0.155.0
* Client OS: MacOS

### PR DESCRIPTION
**Pull request by tleunen**
This adds the specific `describe.skip` and `it.skip` and fixes #620.

cc @nmote

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @nmote, @shushz and @pvolok to be potential reviewers.

**Comment by nmote** [comment]
Thanks!

**Comment by nmote** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1025033387551662/int_phab) to review internal test results.

**Pull request closed without merging**
