### PR TITLE
Fix nuclide-start-server certificate validation

### PR DESCRIPTION
**Pull request by Keno**
The version check was failing due to certificate validation failures.
Fix this by:
- disabling host name validation
- passing the CA cert file to the client for validation

Also adds printing for unexpected SSL errors

### CODE REVIEW

**Comment by Keno** [comment]
I see there was a similar pull request in #117, though this one does actually perform the validation. Also what is the minimum required python version for nuclide. It seems like we might need a version check here.

**Comment by bolinfest** [comment]
@Keno just to save us the trouble of auditing: which APIs are you worried are not Python >= 2.6 compliant?

**Comment by Keno** [comment]
the `context` argument to `HTTPSConnection` was introduced when cert validation was enabled by default, which happened in 2.7 I believe.

**Comment by mtorromeo** [comment]
You are missing an import of `ssl`; other than this I'm in favor of merging this instead of my PR#117

**Comment by Keno** [comment]
Updated with missing ssl import.

**Comment by Keno** [comment]
Rebased and added a python version check.

**Comment by Keno** [comment]
Looks like there's merge conflicts again. I'd be happy to rebase this, but please take a look so I can incorporate any review feedback while I'm at it.

**Comment by cbosuna** [comment]
It looks good to me, but will test and get back to you Monday.

**Comment by cbosuna** [comment]
Checked against several versions of python in both the 2.X series and the 3.X series and this patch works like a charm.  I think there is just one tiny merge conflict.  If you fix we can merge this pull request.

**Comment by Keno** [comment]
Rebased.

**Comment by Keno** [comment]
bump again

**Comment by mtorromeo** [comment]
After 2 months, a fix this simple is not merged yet.
Even if one is willing to contribute you end up not even bothering anymore...

**Comment by ssorallen** [comment]
@cbosuna Is there anything blocking this?

**Comment by Keno** [comment]
Time for my monthly bump ;).

**Comment by Keno** [comment]
Thanks, just in time ;)

**Pull request closed without merging**
