### PR TITLE
Fixing regex for get openssh common_name #1341

### PR DESCRIPTION
**Pull request by Empornium**

### CODE REVIEW

**Comment by hansonw** [comment]
Looks good, just needs the CLA signing!

**Comment by Empornium** [comment]
Not our code, code came from fanch317.

**Comment by hansonw** [comment]
Right, but since you're submitting the pull request you have to sign the agreement (since it's tied to you). If that's a blocker for some reason I can pull this in manually.

**Comment by Empornium** [comment]
Yeah, please pull it in manually.

**Pull request closed without merging**
